export const SUPERVISOR_LIST_REQUEST = "SUPERVISOR_LIST_REQUEST";
export const SUPERVISOR_LIST_SUCCESS = "SUPERVISOR_LIST_SUCCESS";
export const SUPERVISOR_LIST_FAIL = "SUPERVISOR_LIST_FAIL";
export const REMOVE_SUPERVISOR_SUCCESS = "REMOVE_SUPERVISOR_SUCCESS";

export const INSTI_COURSE_LIST_REQUEST = "INSTI_COURSE_LIST_REQUEST";
export const INSTI_COURSE_LIST_SUCCESS = "INSTI_COURSE_LIST_SUCCESS";
export const INSTI_COURSE_LIST_FAIL = "INSTI_COURSE_LIST_FAIL";
