export const SUPERVISOR_LIST_REQUEST = "SUPERVISOR_LIST_REQUEST";
export const SUPERVISOR_LIST_SUCCESS = "SUPERVISOR_LIST_SUCCESS";
export const SUPERVISOR_LIST_FAIL = "SUPERVISOR_LIST_FAIL";
export const REMOVE_SUPERVISOR_SUCCESS = "REMOVE_SUPERVISOR_SUCCESS";
