export const SUPERVISOR_LIST_REQUEST = "SUPERVISOR_LIST_REQUEST";
export const SUPERVISOR_LIST_SUCCESS = "SUPERVISOR_LIST_SUCCESS";
export const SUPERVISOR_LIST_FAIL = "SUPERVISOR_LIST_FAIL";
export const REMOVE_SUPERVISOR_SUCCESS = "REMOVE_SUPERVISOR_SUCCESS";

export const INSTI_COURSE_LIST_REQUEST = "INSTI_COURSE_LIST_REQUEST";
export const INSTI_COURSE_LIST_SUCCESS = "INSTI_COURSE_LIST_SUCCESS";
export const INSTI_COURSE_LIST_FAIL = "INSTI_COURSE_LIST_FAIL";

export const INSTRUCTOR_LIST_REQUEST = "INSTRUCTOR_LIST_REQUEST";
export const INSTRUCTOR_LIST_SUCCESS = "INSTRUCTOR_LIST_SUCCESS";
export const INSTRUCTOR_LIST_FAIL = "INSTRUCTOR_LIST_FAIL";
export const ADD_INSTRUCTOR_SUCCESS = "ADD_INSTRUCTOR_SUCCESS";

export const STUDENT_LIST_REQUEST = "STUDENT_LIST_REQUEST";
export const STUDENT_LIST_SUCCESS = "STUDENT_LIST_SUCCESS";
export const STUDENT_LIST_FAIL = "STUDENT_LIST_FAIL";
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS";
