export const EMPLOYEE_PROFILE_REQUEST = "EMPLOYEE_PROFILE_REQUEST";
export const EMPLOYEE_PROFILE_SUCCESS = "EMPLOYEE_PROFILE_SUCCESS";
export const EMPLOYEE_PROFILE_FAIL = "EMPLOYEE_PROFILE_FAIL";

export const INSTITUTE_PROFILE_REQUEST = "INSTITUTE_PROFILE_REQUEST";
export const INSTITUTE_PROFILE_SUCCESS = "INSTITUTE_PROFILE_SUCCESS";
export const INSTITUTE_PROFILE_FAIL = "INSTITUTE_PROFILE_FAIL";
